# Generated by Django 4.0.1 on 2022-01-13 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(editable=False)),
                ('end_time', models.DateTimeField(editable=False)),
                ('booker_email', models.CharField(editable=False, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('slug', models.CharField(editable=False, max_length=256, unique=True)),
                ('duration', models.IntegerField(choices=[(1, '15 min'), (2, '30 min'), (3, '45 min'), (4, '60 min')], default=1, help_text='Duration of event in minutes')),
                ('horizon', models.PositiveIntegerField(help_text='How far out can this event type be scheduled in days?')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.IntegerField(choices=[(1, 'Phone call'), (2, 'Google Meet')], default=1, help_text='1=Phone call, 2=Google Meet')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Only applies to phone call type', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=64)),
                ('sun_start', models.TimeField()),
                ('sun_end', models.TimeField()),
                ('mon_start', models.TimeField()),
                ('mon_end', models.TimeField()),
                ('tue_start', models.TimeField()),
                ('tue_end', models.TimeField()),
                ('wed_start', models.TimeField()),
                ('wed_end', models.TimeField()),
                ('thu_start', models.TimeField()),
                ('thu_end', models.TimeField()),
                ('fri_start', models.TimeField()),
                ('fri_end', models.TimeField()),
                ('sat_start', models.TimeField()),
                ('sat_end', models.TimeField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('sun_start__lt', django.db.models.expressions.F('sun_end'))), name='sun_time_range'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('mon_start__lt', django.db.models.expressions.F('mon_end'))), name='mon_time_range'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('tue_start__lt', django.db.models.expressions.F('tue_end'))), name='tue_time_range'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('wed_start__lt', django.db.models.expressions.F('wed_end'))), name='wed_time_range'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('thu_start__lt', django.db.models.expressions.F('thu_end'))), name='thu_time_range'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('fri_start__lt', django.db.models.expressions.F('fri_end'))), name='fri_time_range'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('sat_start__lt', django.db.models.expressions.F('sat_end'))), name='sat_time_range'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('location_type', 2)), fields=('location_type',), name='one_google_meet_type'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.eventtype'),
        ),
    ]
