# Generated by Django 4.0.1 on 2022-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='horizon',
            field=models.PositiveIntegerField(choices=[(1, '30 days'), (2, '60 days'), (3, '90 days')], default=1, help_text='How far out can this event type be scheduled in days?'),
        ),
    ]
