# Generated by Django 4.0.1 on 2022-01-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_eventtype_horizon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booker_name',
            field=models.CharField(default='First Last', max_length=64),
            preserve_default=False,
        ),
    ]
