# Generated by Django 4.0.1 on 2022-01-14 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_event_booker_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'availability schedule'},
        ),
        migrations.AddField(
            model_name='eventtype',
            name='schedule',
            field=models.ForeignKey(default=1, help_text='Schedule to use for availability hours', on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule'),
            preserve_default=False,
        ),
    ]
