# Generated by Django 4.0.1 on 2022-01-14 06:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_schedule_options_eventtype_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.IntegerField(editable=False, help_text='1=Phone call, 2=Google Meet', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, editable=False, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='booker_email',
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='booker_name',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='horizon',
            field=models.IntegerField(choices=[(1, '30 days'), (2, '60 days'), (3, '90 days')], default=1, help_text='How far out can this event type be scheduled in days?'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='slug',
            field=models.SlugField(editable=False, max_length=64, unique=True),
        ),
    ]
