# Generated by Django 4.0.1 on 2022-01-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_event_event_type_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='sun_time_range',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='mon_time_range',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='tue_time_range',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='wed_time_range',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='thu_time_range',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='fri_time_range',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='sat_time_range',
        ),
        migrations.AddField(
            model_name='schedule',
            name='fri_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='mon_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sat_off',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sun_off',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thu_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tue_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wed_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fri_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fri_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mon_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mon_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sat_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sat_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sun_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sun_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thu_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thu_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tue_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tue_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wed_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wed_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
