# Generated by Django 4.0.1 on 2022-01-19 07:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_remove_schedule_sun_time_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_name',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(choices=[(15, '15 min'), (30, '30 min'), (45, '45 min'), (60, '60 min')], default=15, help_text='Duration of event in minutes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_type',
            field=models.CharField(choices=[('Phone call', 'Phone Call'), ('Google Meet', 'Google Meet')], default='Phone call', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
